### ISSUE TITLE
Incorrect Response

### ISSUE THREAD

**Issue by tfalamu** [Mastersam07/ncovid-19-api#6]
API results don't seem to match those on the NCDC website

**Comment by Mastersam07** [comment]
Seems the data has been rearranged on NCDC website causing the scrapers not to auto-update successfully.

**Comment by Mastersam07** [comment]
The issue is now being treated.

**Comment by tfalamu** [comment]
Terrific. How soon will there be a fix?

**Comment by Mastersam07** [comment]
Less than an hour. I am making some commits already.

**Comment by Mastersam07** [comment]
Issue fixed in the latest commit. The API structure is also maintained.

**Comment by tfalamu** [comment]
Awesome, thanks. One more question, how often is the data refreshed?

**Comment by Mastersam07** [comment]
NCDC gives their update somewhere around 10 pm. The scrapers are set to refresh the data by 11:30 pm in case NCDC gives their update late.

**Comment by tfalamu** [comment]
Terrific, glad an api like this is available. Saves me a whole bunch of time.

**Comment by Mastersam07** [comment]
😁😁😁.......... You could send a PR and add your app/solution to the showcase area of the readme if you see it fit.

**Comment by Mastersam07** [comment]
Will close this issue if there's nothing else.🙂

**Comment by tfalamu** [comment]
Definitely, I'll be honored!

**Comment by tfalamu** [comment]
I think I have all I need for now, you can close the issue.

**Comment by Mastersam07** [comment]
This issue has been fixed and is now closed
