### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Mastersam07** [Mastersam07/ncovid-19-api#8]
API has not been consistent due to changes in the data structure on NCDC site. API data could go stale for almost 24hours due to delay in updating data on NCDC site. A new feature is being made to fetch the data every 3hours and account for changes in data structure. This should be a lasting fix as API structure must be maintained.

**Comment by Mastersam07** [comment]
Fixed this and #6

**Comment by tfalamu** [comment]
Terrific. The update schedule you explained is still maintained right?

**Comment by Mastersam07** [comment]
Yes. The update schedule is maintained
